### ISSUE TITLE
没有增加头部和尾部视图的功能吗？可以增加不

### ISSUE THREAD

**Issue by Lsy1992** [twiceyuan/CommonAdapter#7]

**Comment by twiceyuan** [comment]
你好，可以试试 https://github.com/twiceyuan/CommonAdapter/blob/master/library/src/main/java/com/twiceyuan/commonadapter/library/adapter/WrapperAdapter.java

**Comment by twiceyuan** [comment]
示例用法可以参考https://github.com/twiceyuan/CommonAdapter/blob/master/sample/src/main/java/com/twiceyuan/commonadapter/sample/wrapperSample/WrapperSampleActivity.java
