### ISSUE TITLE
字节码类型对象调用 newInstance() 报错： a zero-argument-constructor 

### ISSUE THREAD

**Issue by hanchanpo13** [twiceyuan/CommonAdapter#9]
当viewholder是activity内部类时，com/xzdz/common/widget/adapter/utils/AdapterUtil.java:63
![image](https://user-images.githubusercontent.com/8656222/52995676-47538b00-3456-11e9-8dcd-c8a41ee81078.png)
报错  a zero-argument-constructor

**Comment by twiceyuan** [comment]
Holder 类需要有一个空参数构造器，否则无法通过反射来实例化

**Comment by twiceyuan** [comment]
如果是内部类的话，建议对 class 加上 `public static` 修饰符
